apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: nginx-ingress
  annotations:
    meta.helm.sh/release-name: base-edit
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm